export const getTestRecipe = () => {
  const recipe = {
    preparationMinutes: 10,
    cookingMinutes: 45,
    aggregateLikes: 1866,
    healthScore: 100,
    creditsText: 'pinkwhen.com',
    sourceName: 'pinkwhen.com',
    pricePerServing: 300.45,
    extendedIngredients: [
      {
        id: 9037,
        aisle: 'Produce',
        image: 'avocado.jpg',
        consistency: 'SOLID',
        name: 'additional toppings: avocado',
        nameClean: 'avocado',
        original: 'additional toppings: diced avocado, micro greens, chopped basil)',
        originalName: 'additional toppings: diced avocado, micro greens, chopped basil)',
        amount: 8.0,
        unit: 'servings',
        meta: ['diced', 'chopped'],
        measures: {
          us: {
            amount: 8.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 8.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 3.0,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 0.1,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 0.25,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 0.25,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'SOLID',
        name: 'carrots',
        nameClean: 'carrot',
        original: '3 medium carrots, peeled and diced',
        originalName: 'carrots, peeled and diced',
        amount: 1.5,
        unit: 'medium',
        meta: ['diced', 'peeled'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
          metric: {
            amount: 3.0,
            unitShort: 'medium',
            unitLong: 'mediums',
          },
        },
      },
    ],
    id: 715415,
    title: 'Red Lentil Soup with Chicken and Turnips',
    readyInMinutes: 55,
    servings: 8,
    sourceUrl: 'https://www.pinkwhen.com/red-lentil-soup-with-chicken-and-turnips/',
    image: 'https://img.spoonacular.com/recipes/715415-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Red Lentil Soup with Chicken and Turnips might be a good recipe to expand your main course repertoire. This recipe serves 8 and costs $3.0 per serving. One serving contains <b>477 calories</b>, <b>27g of protein</b>, and <b>20g of fat</b>. It is brought to you by Pink When. 1866 people have tried and liked this recipe. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. From preparation to the plate, this recipe takes approximately <b>55 minutes</b>. It is a good option if you\'re following a <b>gluten free and dairy free</b> diet. Head to the store and pick up salt and pepper, canned tomatoes, flat leaf parsley, and a few other things to make it today. Overall, this recipe earns a <b>spectacular spoonacular score of 99%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-682185">Red Lentil and Chicken Soup</a>, <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-1058971">Red Lentil and Chicken Soup</a>, and <a href="https://spoonacular.com/recipes/red-lentil-soup-34121">Red-Lentil Soup</a>.',
    instructions:
      'To a large dutch oven or soup pot, heat the olive oil over medium heat. Add the onion, carrots and celery and cook for 8-10 minutes or until tender, stirring occasionally. Add the garlic and cook for an additional 2 minutes, or until fragrant. Season conservatively with a pinch of salt and black pepper.To the pot, add the tomatoes, turnip and red lentils. Stir to combine. Stir in the vegetable stock and increase the heat on the stove to high. Bring the soup to a boil and then reduce to a simmer. Simmer for 20 minutes or until the turnips are tender and the lentils are cooked through. Add the chicken breast and parsley. Cook for an additional 5 minutes. Adjust seasoning to taste.Serve the soup immediately garnished with fresh parsley and any additional toppings. Enjoy!',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'To a large dutch oven or soup pot, heat the olive oil over medium heat.',
            ingredients: [
              {
                id: 4053,
                name: 'olive oil',
                localizedName: 'olive oil',
                image: 'olive-oil.jpg',
              },
              {
                id: 0,
                name: 'soup',
                localizedName: 'soup',
                image: '',
              },
            ],
            equipment: [
              {
                id: 404667,
                name: 'dutch oven',
                localizedName: 'dutch oven',
                image: 'https://spoonacular.com/cdn/equipment_100x100/dutch-oven.jpg',
              },
            ],
          },
          {
            number: 2,
            step: 'Add the onion, carrots and celery and cook for 8-10 minutes or until tender, stirring occasionally.',
            ingredients: [
              {
                id: 11124,
                name: 'carrot',
                localizedName: 'carrot',
                image: 'sliced-carrot.png',
              },
              {
                id: 11143,
                name: 'celery',
                localizedName: 'celery',
                image: 'celery.jpg',
              },
              {
                id: 11282,
                name: 'onion',
                localizedName: 'onion',
                image: 'brown-onion.png',
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: 'minutes',
            },
          },
        ],
      },
    ],
  };

  return recipe;
};
